; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "My Program"
#define MyAppVersion "1.5"
#define MyAppPublisher "My Company, Inc."
#define MyAppURL "https://www.example.com/"
#define MyAppExeName "MyProg-x64.exe"
#define MyAppAssocName MyAppName + " File"
#define MyAppAssocExt ".myp"
#define MyAppAssocKey StringChange(MyAppAssocName, " ", "") + MyAppAssocExt

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{71D2CCB6-F1DA-4EBF-960C-DB9BA9FF3055}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
UninstallDisplayIcon={app}\{#MyAppExeName}
; "ArchitecturesAllowed=x64compatible" specifies that Setup cannot run
; on anything but x64 and Windows 11 on Arm.
ArchitecturesAllowed=x64compatible
; "ArchitecturesInstallIn64BitMode=x64compatible" requests that the
; install be done in "64-bit mode" on x64 or Windows 11 on Arm,
; meaning it should use the native 64-bit Program Files directory and
; the 64-bit view of the registry.
ArchitecturesInstallIn64BitMode=x64compatible
ChangesAssociations=yes
DisableProgramGroupPage=yes
; Uncomment the following line to run in non administrative install mode (install for current user only).
;PrivilegesRequired=lowest
OutputBaseFilename=mysetup
SolidCompression=yes
WizardStyle=modern

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "E:\install\my app\.env"; DestDir: "{app}"; Flags: replacesameversion
Source: "E:\install\my app\nssm.exe"; DestDir: "{app}"; Flags: replacesameversion
Source: "E:\install\my app\script_install.bat"; DestDir: "{app}"; Flags: ignoreversion replacesameversion
Source: "E:\install\my app\uninstaller.bat"; DestDir: "{app}"; Flags: replacesameversion
Source: "E:\install\my app\AppElectron.exe"; DestDir: "{app}"; Flags: deleteafterinstall isreadme replacesameversion
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Registry]
Root: HKLM; Subkey: "SYSTEM\CurrentControlSet\Control\Session Manager\Environment"; ValueType: string; ValueName: "URL_API"; ValueData: "{code:GetUrlApi}"; Flags: dontcreatekey uninsdeletevalue
Root: HKLM; Subkey: "SYSTEM\CurrentControlSet\Control\Session Manager\Environment"; ValueType: string; ValueName: "APP_PRODUCT_VERSION.MY_APP"; ValueData: "{#MyAppVersion}"; Flags: dontcreatekey uninsdeletevalue

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\script_install.bat"; Parameters: "/silent"; Flags: waituntilterminated skipifdoesntexist runascurrentuser runhidden; StatusMsg: "Service installation. Please wait..."

[UninstallRun]
Filename: "{app}\uninstaller.bat"; Flags: waituntilterminated runascurrentuser runhidden; RunOnceId: "remove"

Filename: {sys}\sc.exe; Parameters: "stop my_app" ; Flags: runhidden; RunOnceId: "DelService"
Filename: {sys}\sc.exe; Parameters: "delete my_app" ; Flags: runhidden; RunOnceId: "DelService"

[Code]
var ConfigPage: TInputQueryWizardPage;
RegistryValue: Boolean;
procedure AddConfigPage();
begin
  ConfigPage := CreateInputQueryPage(
    wpWelcome,
    'Configuration',
    'Input info',
    'Custom instructions');

  { Add items (False means it's not a password edit) }
  ConfigPage.Add('URL_API (exp http://10.10.32.106:5000/api/):', False);

end;

function GetUrlApi(Param: string): string;
begin
  if Assigned(ConfigPage) then
  begin
    Result := ConfigPage.Values[0];
  end
  else
  begin
    RegistryValue := RegValueExists(HKEY_LOCAL_MACHINE, 'SYSTEM\CurrentControlSet\Control\Session Manager\Environment', 'URL_API');
    if RegistryValue then
      begin
        if not RegQueryStringValue(HKEY_LOCAL_MACHINE, 'SYSTEM\CurrentControlSet\Control\Session Manager\Environment', 'URL_API', Result) then
        begin
          // Failed to read the registry value, handle the error here if needed
          Result := '';
        end;
      end
    else
      begin
        Result := 'Error Value';
        // or use a default value like:
        // Result := 'DEFAULT_VALUE';
      end;
  end;
end;

procedure InitializeWizard();
begin
  UrlApiExists := RegValueExists(HKEY_LOCAL_MACHINE, 'SYSTEM\CurrentControlSet\Control\Session Manager\Environment', 'URL_API');
  
  if not (UrlApiExists) then
    AddConfigPage();
end;
